"""
report.py
Generates a standalone HTML report for a traffic analysis run.
"""
import os
import datetime

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Traffic Analysis Report</title>
<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600;800&display=swap" rel="stylesheet">
<style>
  :root {{ --bg:#060a07; --panel:#0b120d; --border:#1c3322; --green:#39ff88; --dim:#6f9c81; --red:#ff4d5e; --amber:#ffd166; --text:#d5f5e0; }}
  * {{ box-sizing:border-box; }}
  body {{ background:var(--bg); color:var(--text); font-family:'JetBrains Mono',monospace; padding:32px; max-width:900px; margin:0 auto; }}
  h1 {{ color:var(--green); font-size:22px; }}
  .meta {{ color:var(--dim); font-size:13px; margin-bottom:24px; }}
  .panel {{ background:var(--panel); border:1px solid var(--border); border-radius:4px; padding:16px; margin-bottom:20px; }}
  .panel h3 {{ color:var(--green); margin-top:0; font-size:14px; }}
  table {{ width:100%; border-collapse:collapse; font-size:13px; }}
  td {{ padding:6px 4px; border-bottom:1px solid rgba(28,51,34,0.5); }}
  .sev-HIGH {{ color:var(--red); font-weight:700; }}
  .sev-MEDIUM {{ color:var(--amber); font-weight:700; }}
  .footer {{ color:var(--dim); font-size:11px; margin-top:24px; }}
</style>
</head>
<body>
  <h1>&gt; traffic_analysis_report.log</h1>
  <div class="meta">source: {source} &nbsp;·&nbsp; generated_at: {generated_at} &nbsp;·&nbsp;
  total packets: {total} &nbsp;·&nbsp; IPv4: {ipv4}</div>

  <div class="panel"><h3>protocol_breakdown</h3><table>{proto_rows}</table></div>
  <div class="panel"><h3>top_talkers</h3><table>{talker_rows}</table></div>
  <div class="panel"><h3>top_destination_ports</h3><table>{port_rows}</table></div>
  <div class="panel"><h3>alerts ({alert_count})</h3><table>{alert_rows}</table></div>

  <div class="footer">Generated by Network Traffic Analyzer · from-scratch pcap parsing</div>
</body>
</html>
"""


def generate_html_report(source, summary, alerts, out_dir=None):
    out_dir = out_dir or os.path.join(os.path.dirname(__file__), "..", "reports")
    os.makedirs(out_dir, exist_ok=True)

    proto_rows = "".join(f"<tr><td>{k}</td><td>{v}</td></tr>" for k, v in summary["protocol_counts"].items())
    talker_rows = "".join(f"<tr><td>{ip}</td><td>{c}</td></tr>" for ip, c in summary["top_talkers"])
    port_rows = "".join(f"<tr><td>{p}</td><td>{c}</td></tr>" for p, c in summary["top_dest_ports"])
    alert_rows = "".join(
        f"<tr><td class='sev-{a['severity']}'>{a['severity']}</td><td>{a['type']}</td><td>{a['message']}</td></tr>"
        for a in alerts
    ) or "<tr><td colspan=3>No alerts</td></tr>"

    html = TEMPLATE.format(
        source=source, generated_at=datetime.datetime.now().isoformat(),
        total=summary["total_packets"], ipv4=summary["ipv4_packets"],
        proto_rows=proto_rows, talker_rows=talker_rows, port_rows=port_rows,
        alert_count=len(alerts), alert_rows=alert_rows,
    )

    path = os.path.join(out_dir, f"traffic_report_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.html")
    with open(path, "w") as f:
        f.write(html)
    return path
